
FROM node:14-alpine as build  
WORKDIR /app
COPY package*.json ./
#RUN yarn install
RUN npm install --global @gridsome/cli
COPY . /app

#Install dependincy
RUN yarn global upgrade --latest @vue/cli



# production stage
FROM nginx:1.15.7-alpine

COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
